# workflow的名称，会显示在工作流运行页面
name: MainWorkflow

# 工作流执行的契机：push表示每次push代码之后都会执行
on: [push]

jobs:
  # build job 我们用来做持续构建
  build:
    runs-on: ubuntu-latest
    steps:
        # 设置阿里云OSS的 id/secret，存储到 github 的 secrets 中
      - name: setup aliyun oss
      - uses: actions/checkout@master
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-beijing.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
     - name: cp files to aliyun
    #  - run: ossutil cp /src oss://iptttv/ -rf
     - run: ossutil cp -rf src oss://iptttv/

   
